version: '3.8'

services:
  rag-system:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - VECTOR_DB_TYPE=chroma
      - CHROMA_PERSIST_DIR=/app/data/vectorstore/chroma
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: rag_network
